name: tryhard_showcase
description: TRYHARD app showcase

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  email_validator: ^2.1.17
  equatable: ^2.0.5
  json_serializable: ^6.0.1
  fluttertoast: ^8.0.9
  flutter_svg: ^1.0.0
  intl: ^0.17.0
  path_provider: ^2.0.11
  #  provider: ^6.0.1
  uuid: ^3.0.5
  given_when_then: ^0.2.0

  #firebase
  google_sign_in: ^5.4.1
  cloud_firestore: ^4.1.0
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.4
  firebase_storage: ^11.0.6
  mockito: ^5.3.2

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/

  fonts:
    - family: SairaSemiCondensed
      fonts:
        - asset: assets/fonts/SairaSemiCondensed-Thin.ttf
          weight: 200
        - asset: assets/fonts/SairaSemiCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/SairaSemiCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/SairaSemiCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/SairaSemiCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SairaSemiCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/SairaSemiCondensed-Black.ttf
          weight: 900
