name: tryhard_showcase
description: TRYHARD app showcase

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  assets_audio_player: ^3.0.6
  email_validator: ^2.1.17
  equatable: ^2.0.5
  json_serializable: ^6.6.1
  fluttertoast: ^8.2.1
  flutter_bloc: ^8.1.2
  flutter_svg: ^2.0.4
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  intl: ^0.17.0
  path_provider: ^2.0.14
  uuid: ^3.0.5
  given_when_then: ^0.2.0
  google_sign_in: ^6.1.0
  cloud_firestore: ^4.5.0
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  firebase_storage: ^11.1.0
  go_router: ^6.5.5
  get_it: ^7.2.0
  injectable: ^2.1.1
  injectable_generator: ^2.1.5
  hydrated_bloc: ^9.1.0
  json_annotation: ^4.8.0
  bloc_test: ^9.1.1
  rive: ^0.10.4
  golden_toolkit: ^0.15.0


dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^2.0.1
  mocktail: ^0.3.0
  flutter_test:
    sdk: flutter
  lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/

  fonts:
    - family: SairaSemiCondensed
      fonts:
        - asset: assets/fonts/SairaSemiCondensed-Thin.ttf
          weight: 200
        - asset: assets/fonts/SairaSemiCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/SairaSemiCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/SairaSemiCondensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/SairaSemiCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SairaSemiCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/SairaSemiCondensed-Black.ttf
          weight: 900
